### PR TITLE
Add LICENSE file and update README

### LINKED ISSUE #12: Please add LICENSE file
It is requirement when packaging for various Linux distributions.

### PR DESCRIPTION
**Pull request by massand**
The LICENSE file is required for Linux packaging. The README has been updated to match the LICENSE file. This fixes #12.

### CODE REVIEW

**Comment by hannobraun** [comment]
Thank you, @massand!

Is merging this pull request enough to satisfy any Linux packaging requirements, or do I need to release a new version (that includes this LICENSE file) on crates.io?

**Comment by massand** [comment]
To pick up the license file, a new version would need to be published on crate.io. The latest version of the cargo tool (`cargo publish` or `cargo package` commands) should automatically pull in the LICENSE file path into crate metadata. You may also need to publish a new version of inotify and notify crates for this to be picked up, depending on version used to publish this chain of crates.

**Comment by hannobraun** [comment]
Thank you, I'll publish a new version as soon as I find some time.

There have been no breaking changes since the last release, so this can just be published as 0.1.5, which means it'll be picked up by dependencies automatically. A new inotify release should not be necessary, and I  have no power over notify anyway.

**Comment by hannobraun** [comment]
Version 0.1.5 has been published.

**Comment by massand** [comment]
@hannobraun Any plans to bump the release for `inotify-rs` to pick up the `inotify-sys 0.1.5` crate? `inotify 0.9.2` depends on `inotify-sys 0.1.3`.

**Comment by hannobraun** [comment]
As I said earlier, the new version will be picked up by dependencies automatically. `inotify-sys = "0.1.3"` is the same as `inotify-sys = "^0.1.3"`, which means `>=0.1.3, <0.2.0` ([documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html)).

Unless other crates in the build prevent it by using more specific version requirements, the newest version will always be chosen when running `cargo update`, or when running a build without an existing `Cargo.lock`.

**Pull request merged**
